[project]
name = "hacknotts25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "fastapi>=0.120.0",
    "ollama>=0.6.0",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.44",
]
